

import { Category } from './types';
import {
  LazerNaturezaIcon,
  AlimentacaoBebidasIcon,
  EventosEntretenimentoIcon,
  CulturaTurismoIcon,
  HospedagemIcon,
  ComercioServicosIcon,
  EsporteLazerAtivoIcon,
  InfantilFamiliaIcon,
  MobilidadeApoioIcon,
  SaudeBemEstarIcon,
  EducacaoIcon,
} from './components/icons';

export const CATEGORIES: Category[] = [
  {
    id: 'lazer-natureza',
    name: 'LAZER & NATUREZA',
    icon: <LazerNaturezaIcon />,
    subcategories: [
      { id: 'campings', name: 'Campings' },
      { id: 'parques-nacionais', name: 'Parques nacionais' },
      { id: 'parques-estaduais', name: 'Parques estaduais' },
      { id: 'parques-municipais', name: 'Parques municipais' },
      { id: 'praias', name: 'Praias' },
      { id: 'cachoeiras', name: 'Cachoeiras' },
      { id: 'trilhas', name: 'Trilhas' },
      { id: 'mirantes', name: 'Mirantes' },
      { id: 'pracas-publicas', name: 'Praças públicas' },
      { id: 'jardins-botanicos', name: 'Jardins botânicos' },
      { id: 'reservas-naturais', name: 'Reservas naturais' },
      { id: 'zoologicos', name: 'Zoológicos' },
      { id: 'aquarios', name: 'Aquários' },
    ],
  },
  {
    id: 'alimentacao-bebidas',
    name: 'ALIMENTAÇÃO & BEBIDAS',
    icon: <AlimentacaoBebidasIcon />,
    subcategories: [
      { id: 'restaurantes', name: 'Restaurantes' },
      { id: 'restaurantes-self-service', name: 'Restaurantes self-service' },
      { id: 'restaurantes-a-la-carte', name: 'Restaurantes à la carte' },
      { id: 'bares', name: 'Bares' },
      { id: 'botecos', name: 'Botecos' },
      { id: 'lanchonetes', name: 'Lanchonetes' },
      { id: 'hamburguerias', name: 'Hamburguerias' },
      { id: 'pizzarias', name: 'Pizzarias' },
      { id: 'sorveterias', name: 'Sorveterias' },
      { id: 'cafeterias', name: 'Cafeterias' },
      { id: 'padarias', name: 'Padarias' },
      { id: 'docerias', name: 'Docerias' },
      { id: 'churrascarias', name: 'Churrascarias' },
      { id: 'food-trucks', name: 'Food trucks' },
      { id: 'quiosques', name: 'Quiosques' },
      { id: 'adegas-emporios', name: 'Adegas / empórios' },
    ],
  },
  {
    id: 'eventos-entretenimento',
    name: 'EVENTOS & ENTRETENIMENTO',
    icon: <EventosEntretenimentoIcon />,
    subcategories: [
      { id: 'festas', name: 'Festas' },
      { id: 'festas-populares', name: 'Festas populares' },
      { id: 'baladas', name: 'Baladas' },
      { id: 'casas-noturnas', name: 'Casas noturnas' },
      { id: 'shows', name: 'Shows' },
      { id: 'eventos-culturais', name: 'Eventos culturais' },
      { id: 'feiras', name: 'Feiras' },
      { id: 'feiras-gastronomicas', name: 'Feiras gastronômicas' },
      { id: 'festivais', name: 'Festivais' },
      { id: 'rodeios', name: 'Rodeios' },
      { id: 'exposicoes', name: 'Exposições' },
      { id: 'eventos-esportivos', name: 'Eventos esportivos' },
    ],
  },
  {
    id: 'cultura-turismo',
    name: 'CULTURA & TURISMO',
    icon: <CulturaTurismoIcon />,
    subcategories: [
      { id: 'pontos-turisticos', name: 'Pontos turísticos' },
      { id: 'museus', name: 'Museus' },
      { id: 'centros-culturais', name: 'Centros culturais' },
      { id: 'teatros', name: 'Teatros' },
      { id: 'cinemas', name: 'Cinemas' },
      { id: 'igrejas-historicas', name: 'Igrejas históricas' },
      { id: 'monumentos', name: 'Monumentos' },
      { id: 'centros-historicos', name: 'Centros históricos' },
      { id: 'bibliotecas', name: 'Bibliotecas' },
    ],
  },
  {
    id: 'hospedagem',
    name: 'HOSPEDAGEM',
    icon: <HospedagemIcon />,
    subcategories: [
      { id: 'hoteis', name: 'Hotéis' },
      { id: 'pousadas', name: 'Pousadas' },
      { id: 'hostels', name: 'Hostels' },
      { id: 'resorts', name: 'Resorts' },
      { id: 'flats', name: 'Flats' },
      { id: 'chales', name: 'Chalés' },
      { id: 'airbnb-aluguel-temporada', name: 'Airbnb / aluguel por temporada' },
      { id: 'campings-estruturados', name: 'Campings estruturados' },
    ],
  },
  {
    id: 'comercio-servicos',
    name: 'COMÉRCIO & SERVIÇOS',
    icon: <ComercioServicosIcon />,
    subcategories: [
      { id: 'shoppings', name: 'Shoppings' },
      { id: 'lojas', name: 'Lojas' },
      { id: 'feiras-livres', name: 'Feiras livres' },
      { id: 'mercados', name: 'Mercados' },
      { id: 'supermercados', name: 'Supermercados' },
      { id: 'farmacias', name: 'Farmácias' },
      { id: 'saloes-de-beleza', name: 'Salões de beleza' },
      { id: 'barbearias', name: 'Barbearias' },
      { id: 'academias', name: 'Academias' },
      { id: 'clinicas', name: 'Clínicas' },
      { id: 'lavanderias', name: 'Lavanderias' },
    ],
  },
  {
    id: 'esporte-lazer-ativo',
    name: 'ESPORTE & LAZER ATIVO',
    icon: <EsporteLazerAtivoIcon />,
    subcategories: [
      { id: 'academias', name: 'Academias' },
      { id: 'quadras-esportivas', name: 'Quadras esportivas' },
      { id: 'campos-de-futebol', name: 'Campos de futebol' },
      { id: 'estadios', name: 'Estádios' },
      { id: 'clubes-recreativos', name: 'Clubes recreativos' },
      { id: 'centros-esportivos', name: 'Centros esportivos' },
      { id: 'escolas-de-esporte', name: 'Escolas de esporte' },
      { id: 'pistas-de-skate', name: 'Pistas de skate' },
      { id: 'ciclovias', name: 'Ciclovias' },
    ],
  },
  {
    id: 'infantil-familia',
    name: 'INFANTIL & FAMÍLIA',
    icon: <InfantilFamiliaIcon />,
    subcategories: [
      { id: 'parques-infantis', name: 'Parques infantis' },
      { id: 'buffets-infantis', name: 'Buffets infantis' },
      { id: 'brinquedotecas', name: 'Brinquedotecas' },
      { id: 'parques-tematicos', name: 'Parques temáticos' },
      { id: 'espacos-kids', name: 'Espaços kids' },
      { id: 'zoologicos-infantil', name: 'Zoológicos' },
      { id: 'fazendinhas', name: 'Fazendinhas' },
    ],
  },
  {
    id: 'mobilidade-apoio',
    name: 'MOBILIDADE & APOIO',
    icon: <MobilidadeApoioIcon />,
    subcategories: [
      { id: 'estacionamentos', name: 'Estacionamentos' },
      { id: 'postos-de-combustivel', name: 'Postos de combustível' },
      { id: 'pontos-de-onibus', name: 'Pontos de ônibus' },
      { id: 'terminais-rodoviarios', name: 'Terminais rodoviários' },
      { id: 'aeroportos', name: 'Aeroportos' },
      { id: 'locadoras-de-veiculos', name: 'Locadoras de veículos' },
    ],
  },
  {
    id: 'saude-bem-estar',
    name: 'SAÚDE & BEM-ESTAR',
    icon: <SaudeBemEstarIcon />,
    subcategories: [
      { id: 'hospitais', name: 'Hospitais' },
      { id: 'upas', name: 'UPAs' },
      { id: 'clinicas-medicas', name: 'Clínicas médicas' },
      { id: 'clinicas-odontologicas', name: 'Clínicas odontológicas' },
      { id: 'laboratorios', name: 'Laboratórios' },
      { id: 'clinicas-esteticas', name: 'Clínicas estéticas' },
      { id: 'spas', name: 'Spas' },
      { id: 'centros-de-terapia', name: 'Centros de terapia' },
    ],
  },
  {
    id: 'educacao',
    name: 'EDUCAÇÃO',
    icon: <EducacaoIcon />,
    subcategories: [
      { id: 'escolas', name: 'Escolas' },
      { id: 'faculdades', name: 'Faculdades' },
      { id: 'universidades', name: 'Universidades' },
      { id: 'cursos-tecnicos', name: 'Cursos técnicos' },
      { id: 'escolas-de-idiomas', name: 'Escolas de idiomas' },
      { id: 'centros-de-treinamento', name: 'Centros de treinamento' },
    ],
  },
];
